specs-go/config: Make User.UID and User.GID pointers
Avoiding:

  $ go test ./specs-go
  --- FAIL: TestConfigRoundTrip (0.00s)
      --- FAIL: TestConfigRoundTrip/config_2 (0.00s)
          round_trip_test.go:35: failed to round-trip:
                  {"ociVersion":"1.0.0","platform":{"os":"windows","arch":"amd64"},"process":{"user":{"uid":0,"gid":0,"username":"containeradministrator"},"args":["sh"],"cwd":"C:\\"},"root":{"path":"rootfs"}}
  FAIL
  FAIL    github.com/opencontainers/runtime-spec/specs-go 0.003s

We can't just add omitempty (without also making them pointers),
because 0 is a meaningful value for both properties.

Signed-off-by: W. Trevor King <wking@tremily.us>